# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GiphyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GiphyApp
  pod 'SwiftLint'
  pod 'Then'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'RxAnimated'

  target 'GiphyAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GiphyAppUITests' do
    # Pods for testing
  end

end
